fastboot flash boot_a boot_a.img
fastboot flash boot_b boot_b.img
fastboot flash boot_para boot_para.bin
fastboot flash dtbo_a dtbo_a.img
fastboot flash dtbo_b dtbo_b.img
fastboot flash elabel elabel.img
fastboot flash expdb expdb.bin
fastboot flash flashinfo flashinfo.img
fastboot flash frp frp.bin
fastboot flash gz_a gz_a.img
fastboot flash gz_b gz_b.img
fastboot flash journey_persist journey_persist.img
fastboot flash lk_a lk_a.img
fastboot flash lk_b lk_b.img
fastboot flash logo logo.bin
fastboot flash md1img_a md1img_a.img
fastboot flash md1img_b md1img_b.img
fastboot flash md_udc md_udc.bin
fastboot flash metadata metadata.img
fastboot flash misc2 misc2.img
fastboot flash mpt mpt.img
fastboot flash nvcfg nvcfg.img
fastboot flash nvdata nvdata.img
fastboot flash nvram nvram.img
fastboot flash otp otp.img
fastboot flash para para.bin
fastboot flash persist persist.img
fastboot flash pgpt pgpt.bin
fastboot flash preloader preloader.bin
fastboot flash proinfo proinfo.bin
fastboot flash protect1 protect1.img
fastboot flash protect2 protect2.img
fastboot flash scp_a scp_a.img
fastboot flash scp_b scp_b.img
fastboot flash sec1 sec1.bin
fastboot flash seccfg seccfg.bin
fastboot flash spmfw_a spmfw_a.img
fastboot flash spmfw_b spmfw_b.img
fastboot flash sspm_a sspm_a.img
fastboot flash sspm_b sspm_b.img
fastboot flash super super.img
fastboot flash tee_a tee_a.img
fastboot flash tee_b tee_b.img
fastboot flash userdata userdata.img
fastboot flash vbmeta_a vbmeta_a.img
fastboot flash vbmeta_b vbmeta_b.img
fastboot flash vbmeta_system_a vbmeta_system_a.img
fastboot flash vbmeta_system_b vbmeta_system_b.img
fastboot flash vbmeta_vendor_a vbmeta_vendor_a.img
fastboot flash vbmeta_vendor_b vbmeta_vendor_b.img
